version: '3.7'
services:
    database:
        container_name: lootopia_bdd
        image: 'postgres:16-alpine'
        environment:
            - POSTGRES_DB=lootopia_api
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        volumes:
            - database_lootopia_pg:/var/lib/postgresql/data
        ports:
            - '5434:5432'
        networks:
            - lootopia_backend

    php-fpm:
        container_name: lootopia_php-fpm
        build:
            context: ./php-fpm
        depends_on:
            - database
        volumes:
            - ../:/var/www:rw,cached
            - /var/www/var
        networks:
            - lootopia_backend
        environment:
            XDEBUG_CONFIG: >-
                client_host=host.docker.internal
            XDEBUG_MODE: debug
    nginx:
        container_name: lootopia_nginx
        build:
            context: ./nginx
        volumes:
            - ../:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
        networks:
            - lootopia_backend

networks:
  lootopia_backend:

volumes:
    database_lootopia_pg:
